"""empty message

Revision ID: d6aac9d75ef6
Revises: 
Create Date: 2020-08-28 20:01:44.343847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aac9d75ef6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta', sa.String(length=11), nullable=False),
    sa.Column('user', sa.String(length=11), nullable=False),
    sa.Column('agencia', sa.String(length=11), nullable=False),
    sa.Column('saldo', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('extrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_entrada', sa.String(length=16), nullable=False),
    sa.Column('c_saida', sa.Unicode(), nullable=False),
    sa.Column('tipo', sa.Unicode(), nullable=False),
    sa.Column('desc', sa.Unicode(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Unicode(), nullable=False),
    sa.Column('sobrenome', sa.Unicode(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.Unicode(), nullable=False),
    sa.Column('data_nasc', sa.DateTime(), nullable=False),
    sa.Column('data_conta', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('val_email', sa.Boolean(), nullable=False),
    sa.Column('chave', sa.String(length=32), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.Column('cidade', sa.Unicode(), nullable=False),
    sa.Column('estado', sa.Unicode(), nullable=False),
    sa.Column('endereco', sa.Unicode(), nullable=False),
    sa.Column('num', sa.Unicode(), nullable=False),
    sa.Column('cep', sa.Unicode(), nullable=False),
    sa.Column('complemento', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('extrato')
    op.drop_table('conta')
    # ### end Alembic commands ###
